/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package locadoraBO;

import locadoraMODELO.Game;
import locadoraMODELO.Locacoes;
import locadoraMODELO.Genero;
import java.util.List;
import java.util.logging.Level;
import locadoraDAO.*;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author taynara.santos
 */
public class CadastroLocacoes extends javax.swing.JFrame {

    /**
     * Creates new form CadastroAtendimento
     *
     */
    public CadastroLocacoes() throws Exception {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) Locacoes.getModel();
        Locacoes.setRowSorter(new TableRowSorter(modelo));
        lerAtendimento();
        //listarGenero();
        listarGamess();

    }

    public void lerGenero() throws Exception {

        DefaultTableModel modelo = (DefaultTableModel) Locacoes.getModel();
        modelo.setNumRows(0);

        Locacoes.setRowSorter(new TableRowSorter(modelo));

        GeneroDAO med = new GeneroDAO() {
        };

        for (Genero m : med.getAll()) {
            modelo.addRow(new Object[]{
                m.getIdGenero(),
                m.getDescricao()});

        }

    }

    public void lerAtendimento() throws Exception {

        DefaultTableModel modelo = (DefaultTableModel) Locacoes.getModel();
        modelo.setNumRows(0);
        Locacoes.setRowSorter(new TableRowSorter(modelo));

        LocacaoDAO med = new LocacaoDAO() {
        };

        for (Locacoes m : LocacaoDAO.getAll()) {
            modelo.addRow(new Object[]{
                m.getIdLocacao(),
                m.getNomeCliente(),
                m.getIdGame(),
                m.getDtDevolucao(),
                m.getDtLocacao(),
                m.getValor(),
                m.getTelefone()

            });

        }
    }

    public void limparcampos() {

        genero1.setText("");
        valor.setText("");
        nomeCliente.setText("");
        idLocacao.setText("");
        telefone.setText("");
        dtLocacao.setText("");
        dtDevolucao.setText("");
        listaGeneros1.setSelectedIndex(0);

    }

    public void dadosConsultaAtendimento(String atendimento) {

        DefaultTableModel modelo = (DefaultTableModel) Locacoes.getModel();
        modelo.setNumRows(0);

        for (Locacoes atd : LocacaoDAO.buscaLocacoesporId(atendimento)) {
            modelo.addRow(new Object[]{
                atd.getIdLocacao(),
                atd.getNomeCliente(),
                atd.getIdGame()
            });
        }
    }

    private void tornarNaoEditavel() throws Exception {

        telefone.setEditable(false);
        valor.setEditable(false);
        nomeCliente.setEditable(false);
        dtLocacao.setEditable(false);
        dtDevolucao.setEditable(false);

    }

    private void listarGenero() throws Exception {

        List<Genero> todosGeneros;
        todosGeneros = GeneroDAO.getAll();
        todosGeneros.forEach((s) -> {
            listaGeneros1.addItem(s.getDescricao());

        });

    }

    private void listarGamess() throws Exception {

        List<Game> todosGames;
        todosGames = GameDAO.getAll();
        // todosGames = GeneroDAO.getAll();
        todosGames.forEach((s) -> {
            listaGeneros1.addItem(s.getTitulo());

        });

    }

    private void tornarEditavel() throws Exception {

        telefone.setEditable(true);

        valor.setEditable(true);
        nomeCliente.setEditable(true);
        dtLocacao.setEditable(true);
        dtDevolucao.setEditable(true);

    }

   // public void incluirAtendimento() throws Exception GeneroDAO

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        idLocacao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        telefone = new javax.swing.JTextField();
        nomeCliente = new javax.swing.JTextField();
        valor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dtDevolucao = new javax.swing.JFormattedTextField();
        dtLocacao = new javax.swing.JFormattedTextField();
        botaoSair = new javax.swing.JButton();
        botaoSalvar = new javax.swing.JButton();
        botaoAlterar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Locacoes = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        botaoIncluir = new javax.swing.JButton();
        botaoSelecionar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        genero1 = new javax.swing.JTextField();
        listaGeneros1 = new javax.swing.JComboBox<>();
        botaoExcluir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        jLabel1.setText("Código Locação:");

        jLabel2.setText("Cliente");

        jLabel3.setText("Telefone: ");

        valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorActionPerformed(evt);
            }
        });

        jLabel4.setText("Dt. Loc");

        jLabel5.setText("Dt. Dev");

        try {
            dtDevolucao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dtDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtDevolucaoActionPerformed(evt);
            }
        });

        try {
            dtLocacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dtLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtLocacaoActionPerformed(evt);
            }
        });

        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        botaoAlterar.setText("Alterar");
        botaoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("LOCAÇÕES");

        Locacoes.setAutoCreateRowSorter(true);
        Locacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "Game", "Telefone", "Valor", "Data Locação", "Data Devolução"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Locacoes.setColumnSelectionAllowed(true);
        Locacoes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Locacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LocacoesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Locacoes);
        Locacoes.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        botaoIncluir.setText("Incluir");
        botaoIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIncluirActionPerformed(evt);
            }
        });

        botaoSelecionar.setText("Selecionar");
        botaoSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSelecionarActionPerformed(evt);
            }
        });

        jLabel8.setText("Valor:");

        jLabel11.setText("Gênero:");

        listaGeneros1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar..." }));
        listaGeneros1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaGeneros1ActionPerformed(evt);
            }
        });

        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(genero1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listaGeneros1, 0, 1, Short.MAX_VALUE)
                        .addGap(101, 101, 101)
                        .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(botaoAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoIncluir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dtLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(120, 120, 120))
                                    .addComponent(dtDevolucao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valor, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomeCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(589, 589, 589)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1)
                                    .addComponent(botaoSelecionar, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jSeparator2)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoSelecionar)
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dtDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(idLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoSair)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botaoSalvar)
                        .addComponent(botaoAlterar)
                        .addComponent(botaoIncluir)
                        .addComponent(botaoExcluir))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(genero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(listaGeneros1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dtDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtDevolucaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtDevolucaoActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_botaoSairActionPerformed

    private void dtLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtLocacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtLocacaoActionPerformed

    private void botaoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarActionPerformed
        // TODO add your handling code here:

        try {

            tornarEditavel();
            idLocacao.setEditable(false);
            botaoAlterar.setEnabled(false);
            botaoSalvar.setEnabled(false);

        } catch (Exception ex) {
            Logger.getLogger(CadastroGenero.class.getName()).log(Level.SEVERE, null, ex);
        }

        botaoAlterar.setEnabled(false);
        botaoSalvar.setEnabled(true);

        valor.setText("");
        nomeCliente.setText("");


    }//GEN-LAST:event_botaoAlterarActionPerformed

    private void LocacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LocacoesMouseClicked

    }//GEN-LAST:event_LocacoesMouseClicked

    private void botaoIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIncluirActionPerformed
        try {
            // TODO add your handling code here:
            incluirAtendimento();
            lerAtendimento();

        } catch (Exception ex) {
            Logger.getLogger(CadastroLocacoes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoIncluirActionPerformed

    private void botaoSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSelecionarActionPerformed

        GenerosDAO g = new GenerosDAO();
        int pegarCod, j;
        String s = null;
        String xx;
        Locacoes loc;
        Game med;

        pegarCod = Locacoes.getSelectedRow();

        try {

            s = Integer.toString(pegarCod);
            j = (int) Locacoes.getValueAt(pegarCod, 0);

            xx = Integer.toString(j);
            loc = LocacaoDAO.buscarGamePorIdRecLocacao(xx);
            String bg = GenerosDAO.descricaoGenero(loc.getGame());

            genero1.setText(Integer.toString(loc.getGame()));

            xx = Integer.toString(j);
            loc = LocacaoDAO.buscarLocacoesPorId(xx);

            valor.setText(Integer.toString(loc.getValor()));
            nomeCliente.setText(loc.getNomeCliente());
            idLocacao.setText(Integer.toString(j));
            telefone.setText(loc.getTelefone());
            dtLocacao.setText(loc.getDtLocacao());
            dtDevolucao.setText(loc.getDtDevolucao());
            listaGeneros1.setSelectedIndex(j);
            idLocacao.setText(Integer.toString(loc.getIdLocacao()));

            listarGamess();

        } catch (Exception ex) {
            Logger.getLogger(GameDAO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoSelecionarActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        // TODO add your handling code here:

        Locacoes atend = new Locacoes();
        atend.setDtLocacao(dtLocacao.getText());
        atend.setDtDevolucao(dtDevolucao.getText());

        atend.setTelefone(telefone.getText());
        atend.setIdLocacao(Integer.parseInt(idLocacao.getText()));

        try {
            LocacaoDAO.alterarAtendimento(atend);
        } catch (Exception ex) {
            Logger.getLogger(CadastroLocacoes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorActionPerformed

    private void listaGeneros1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaGeneros1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaGeneros1ActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        // TODO add your handling code here:

        int pegarCod, j;
        String s = null;
        String xx;
        Locacoes loc;

        pegarCod = Locacoes.getSelectedRow();

        try {
            System.out.println("PEGAR COD = " + pegarCod);

            s = Integer.toString(pegarCod);
            j = (int) Locacoes.getValueAt(pegarCod, 0);

            xx = Integer.toString(j);
            loc = LocacaoDAO.buscarGamePorIdRecLocacao(xx);

            xx = Integer.toString(j);
            loc = LocacaoDAO.buscarLocacoesPorId(xx);

            LocacaoDAO.excluirLocacao(j);

            lerAtendimento();
            limparcampos();

        } catch (Exception ex) {
            JOptionPane.showInputDialog("\nLocação Excluida \n" + ex);
            Logger.getLogger(GameDAO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroLocacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroLocacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroLocacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroLocacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CadastroLocacoes().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(CadastroLocacoes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Locacoes;
    private javax.swing.JButton botaoAlterar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoIncluir;
    private javax.swing.JButton botaoSair;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JButton botaoSelecionar;
    private javax.swing.JFormattedTextField dtDevolucao;
    private javax.swing.JFormattedTextField dtLocacao;
    private javax.swing.JTextField genero1;
    private javax.swing.JTextField idLocacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JComboBox<Object> listaGeneros1;
    private javax.swing.JTextField nomeCliente;
    private javax.swing.JTextField telefone;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables

}
