package locadoraBO;

import locadoraMODELO.Genero;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import locadoraDAO.*;

public class CadastroGenero extends javax.swing.JFrame {

    /**
     *
     * @throws Exception
     */
    public CadastroGenero() throws Exception {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) genero1.getModel();
        genero1.setRowSorter(new TableRowSorter(modelo));
        listarEspecialidade();

    }

    public void lerGenero() throws Exception {

        DefaultTableModel modelo = (DefaultTableModel) genero1.getModel();
        modelo.setNumRows(0);
        genero1.setRowSorter(new TableRowSorter(modelo));

        GeneroDAO generos = new GeneroDAO() {
        };

        for (Genero genero : generos.getAll()) {
            modelo.addRow(new Object[]{
                genero.getIdGenero(),
                genero.getDescricao()});

        }

    }

    public void excluir() {

        int pegarCod, j, r, x = 0;
        String s = null;
        String z, p, xx;
        int a = 0;

        pegarCod = genero1.getSelectedRow();
        s = Integer.toString(pegarCod);
        j = (int) genero1.getValueAt(pegarCod, 0);

        try {

            r = guardarValorIDparaBUscarGame(j);
            xx = Integer.toString(r);
            GeneroDAO.excluirGenero(r);

            nomeGenero.setText("");
            idGenero.setText("");
            lerGenero();

        } catch (Exception ex) {
            Logger.getLogger(CadastroGenero.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void incluir() {

        botaoNovo.setEnabled(false);
        botaoSalvar.setEnabled(true);

        try {

            Genero g = new Genero();
            g.setDescricao(nomeGenero.getText());

            GeneroDAO.incluir(g.getDescricao());

            lerGenero();
            limpaCampos();

            botaoExcluir.setEnabled(false);
            botaoSalvar.setEnabled(false);
            botaoNovo.setEnabled(true);

        } catch (Exception ex) {
            Logger.getLogger(CadastroGenero.class.getName()).log(Level.SEVERE, null, ex);

        }
    }

    public void selecionar() {

        botaoNovo.setEnabled(false);

        int pegarCod, j, r, x = 0;
        String s = null;
        String z, p, xx;
        int a = 0;
        Genero med = null;

        pegarCod = genero1.getSelectedRow();

        s = Integer.toString(pegarCod);

        j = (int) genero1.getValueAt(pegarCod, 0);

        try {

            botaoLimpar.setEnabled(true);
            botaoSalvar.setEnabled(true);
            botaoAlterar.setEnabled(true);
            botaoExcluir.setEnabled(true);

            r = guardarValorIDparaBUscarGame(j);
            xx = Integer.toString(r);
            med = GeneroDAO.retTabGeneroPeloId(xx);

            nomeGenero.setText(med.getDescricao());
            idGenero.setText(Integer.toString(med.getIdGenero()));

        } catch (Exception ex) {
            Logger.getLogger(CadastroGenero.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void limpaCampos() {
        nomeGenero.setText("");
        idGenero.setText("");
        botaoSalvar.setEnabled(true);
        botaoExcluir.setEnabled(true);
    }

    private void listarEspecialidade() throws Exception {

        lerGenero();

        List<Genero> todosGeneros;
        todosGeneros = GeneroDAO.getAll();
        todosGeneros.forEach((s) -> {

            limpaCampos();

        });

        botaoSalvar.setEnabled(false);
        botaoNovo.setEnabled(true);
        botaoExcluir.setEnabled(false);

    }

    private int guardarValorIDparaBUscarGame(int id) throws Exception {
        int idd = 0;
        idd = id;

        return idd;
    }

    private void tornarNaoEditavel() throws Exception {

        nomeGenero.setEditable(false);
        idGenero.setEditable(false);
    }

    private void tornarEditavel() throws Exception {

        nomeGenero.setEditable(true);
        idGenero.setEditable(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoSair = new javax.swing.JButton();
        botaoAlterar = new javax.swing.JButton();
        botaoSelecionar = new javax.swing.JButton();
        botaoLimpar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        genero1 = new javax.swing.JTable();
        botaoSalvar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        nomeGenero = new javax.swing.JTextField();
        botaoNovo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        idGenero = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        botaoExcluir = new javax.swing.JButton();

        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        botaoAlterar.setText("Alterar");
        botaoAlterar.setEnabled(false);
        botaoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarActionPerformed(evt);
            }
        });

        botaoSelecionar.setText("Selecionar");
        botaoSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSelecionarActionPerformed(evt);
            }
        });

        botaoLimpar.setText("Limpar");
        botaoLimpar.setEnabled(false);
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Gêneros");

        genero1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        genero1.setColumnSelectionAllowed(true);
        genero1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        genero1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                genero1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(genero1);
        genero1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        botaoSalvar.setText("Salvar");
        botaoSalvar.setEnabled(false);
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        jLabel6.setText("Gênero");

        nomeGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeGeneroActionPerformed(evt);
            }
        });

        botaoNovo.setText("Incluir");
        botaoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovoActionPerformed(evt);
            }
        });

        jLabel4.setText("ID");

        idGenero.setEditable(false);
        idGenero.setBorder(null);
        idGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idGeneroActionPerformed(evt);
            }
        });

        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botaoSelecionar)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(idGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(nomeGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botaoExcluir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botaoNovo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botaoLimpar)
                                        .addGap(1, 1, 1)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botaoAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botaoSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoSelecionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(idGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(nomeGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAlterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSair)
                    .addComponent(botaoSalvar)
                    .addComponent(botaoLimpar)
                    .addComponent(botaoNovo)
                    .addComponent(botaoExcluir))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoActionPerformed

        String desc = nomeGenero.getText();

        if (!"".equals(desc)) {

            incluir();

        } else {

            JOptionPane.showMessageDialog(null, "Gentileza informar um nome válido!");
        }


    }//GEN-LAST:event_botaoNovoActionPerformed

    private void nomeGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeGeneroActionPerformed

    private void botaoSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSelecionarActionPerformed
        // TODO add your handling code here:

        try {

            tornarNaoEditavel();
            selecionar();

        } catch (Exception ex) {

            Logger.getLogger(CadastroGenero.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_botaoSelecionarActionPerformed

    private void botaoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarActionPerformed
        try {
            // TODO add your handling code here:

            tornarEditavel();
            idGenero.setEditable(false);
            botaoLimpar.setEnabled(false);

        } catch (Exception ex) {
            Logger.getLogger(CadastroGenero.class.getName()).log(Level.SEVERE, null, ex);
        }

        botaoAlterar.setEnabled(false);

    }//GEN-LAST:event_botaoAlterarActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botaoSairActionPerformed

    private void idGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idGeneroActionPerformed
        // TODO add your handling code here:
        //idMedico.setText(receberMedicoSelecionado.toString());
    }//GEN-LAST:event_idGeneroActionPerformed

    private void genero1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genero1MouseClicked

    }//GEN-LAST:event_genero1MouseClicked

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        // TODO add your handling code here:
        limpaCampos();

    }//GEN-LAST:event_botaoLimparActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed

        try {

            Genero gener = new Genero();

            gener.setIdGenero(Integer.parseInt(idGenero.getText()));
            gener.setDescricao(nomeGenero.getText());
            GeneroDAO.updateGenero(gener);
            listarEspecialidade();
        } catch (Exception ex) {
            Logger.getLogger(CadastroGenero.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        // TODO add your handling code here:

        excluir();
    }//GEN-LAST:event_botaoExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroGenero.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new CadastroGenero().setVisible(true);

            } catch (Exception ex) {
                Logger.getLogger(CadastroGenero.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAlterar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoNovo;
    private javax.swing.JButton botaoSair;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JButton botaoSelecionar;
    private javax.swing.JTable genero1;
    private javax.swing.JTextField idGenero;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nomeGenero;
    // End of variables declaration//GEN-END:variables
}
